---
# Source: nginx-ingress/templates/controller-stats-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.8.9
    component: "controller"
    heritage: Tiller
    release: prodding-hydra
  name: prodding-hydra-nginx-ingress-controller-stats
spec:
  clusterIP: ""
  ports:
    - name: stats
      port: 18080
      targetPort: 18080
  selector:
    app: nginx-ingress
    component: "controller"
    release: prodding-hydra
  type: "ClusterIP"
