---
# Source: nginx-ingress/templates/default-backend-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.8.9
    component: "default-backend"
    heritage: Tiller
    release: prodding-hydra
  name: prodding-hydra-nginx-ingress-default-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ingress
        component: "default-backend"
        release: prodding-hydra
    spec:
      containers:
        - name: nginx-ingress-default-backend
          image: "gcr.io/google_containers/defaultbackend:1.2"
          imagePullPolicy: "IfNotPresent"
          args:
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {}
            
      terminationGracePeriodSeconds: 60
